export const AllowedActions = {
  'list-certificates': ['ROLE_ADMIN', 'ROLE_AGENT'],
  'update-certificates': ['ROLE_ADMIN', 'ROLE_AGENT'],
  'disable-users': ['MANAGE_USERS', 'ROLE_AGENT'],
  'delete-users': ['MANAGE_USERS'],
  'deactivate-users': ['MANAGE_USERS'],
  'deactivate-freelancers': ['MANAGE_USERS', 'MANAGE_FREELANCERS'],
  'view-logs': ['MANAGE_LOGS'],
  'create-users': ['MANAGE_USERS'],
  'manage-freelancers': ['MANAGE_FREELANCERS'],
  'manage-contacts': ['MANAGE_CONTACTS'],
  'manage-ratings': ['MANAGE_RATINGS'],
  'accept-offers': ['MANAGE_PROJECTS'],
  'manage-projects': ['MANAGE_PROJECTS'],
  'manage-clients': ['MANAGE_CUSTOMERS'],
  'manage-orders': ['MANAGE_ORDERS'],
  'manage-invoices': ['MANAGE_INVOICES'],
  'delete-orders': ['MANAGE_ORDERS'],
  'delete-clients': ['MANAGE_CUSTOMERS'],
  'delete-budgets': ['MANAGE_ORDERS'],
  'delete-projects': ['MANAGE_PROJECTS'],
  'reset-invoice': ['RESET_INVOICE'],
  'delete-skill': ['ROLE_ADMIN'],
  'delete-role': ['ROLE_ADMIN'],
};
