import {TimeZoneList} from './timezone.constant';

/*
 * Forms values
 */
export const FormConfig = {
  bicNotRequired: 'DE',
  months: [
    {
      id: 0,
      name: "January"
    },
    {
      id: 1,
      name: "February"
    },
    {
      id: 2,
      name: "March"
    },
    {
      id: 3,
      name: "April"
    },
    {
      id: 4,
      name: "May"
    },
    {
      id: 5,
      name: "June"
    },
    {
      id: 6,
      name: "July"
    },
    {
      id: 7,
      name: "August"
    },
    {
      id: 8,
      name: "September"
    },
    {
      id: 9,
      name: "October"
    },
    {
      id: 10,
      name: "November"
    },
    {
      id: 11,
      name: "December"
    },


  ],
  documents: {
    maxNumberInCollection: 10,
    filePattern: {
      document: '.jpg,.jpeg,.png,.tif,.tiff,.pdf',
      picture: '.jpg,.jpeg,.png,.tif,.tiff',
    },
  },
  master: {
    salutation: ['', 'F', 'M', '-'],
    gender: ['','M', 'F', 'D'],
    languages: [
      '',
      'arabic',
      'czech',
      'dutch',
      'english',
      'french',
      'german',
      'italian',
      'polish',
      'spanish',
      'turkish',
      'other',
    ],
    industryExposure: [
      '',
      'Advertising agencies',
      'Autombiles',
      'Banking and Financial Services',
      'E-commerce',
      'Education',
      'Event Management',
      'Govt. & Public Utilites',
      'Healthcare',
      'Health & Beauty Products',
      'Logistics',
      'Media & Entertainment',
      'NGOs',
      'Real Estate',
      'Recuritment',
      'Restaurants & takeways',
      'Retail',
      'Technology',
      'Travel & Tourism'
    ],
    workPreferences: [
      'I have no wishes and am open to all offers',
      'I would like to work independently',
      'I would like to be busy on a case-by-case basis',
      'I am looking for a permanent job',
      'I want / have to stay below the marginal income limit',
      'I have another job where I am permanently employed',
      'I have another job that I work for occasionally',
      'This is my first time working in Austria',
      'Other'
    ],
    nationalityOrder: ['DE'],
    hasDriversLicense: ['', 'true', 'false'],
    licenseTypes: ['A', 'B', 'C', 'D', 'E', 'F'],
    countries: [
      'AF',
      'AX',
      'AL',
      'DZ',
      'AS',
      'AD',
      'AO',
      'AI',
      'AQ',
      'AG',
      'AR',
      'AM',
      'AW',
      'AU',
      'AT',
      'AZ',
      'BS',
      'BH',
      'BD',
      'BB',
      'BY',
      'BE',
      'BZ',
      'BJ',
      'BM',
      'BT',
      'BO',
      'BQ',
      'BA',
      'BW',
      'BV',
      'BR',
      'IO',
      'BN',
      'BG',
      'BF',
      'BI',
      'KH',
      'CM',
      'CA',
      'CV',
      'KY',
      'CF',
      'TD',
      'CL',
      'CN',
      'CX',
      'CC',
      'CO',
      'KM',
      'CG',
      'CD',
      'CK',
      'CR',
      'CI',
      'HR',
      'CU',
      'CW',
      'CY',
      'CZ',
      'DK',
      'DJ',
      'DM',
      'DO',
      'EC',
      'EG',
      'SV',
      'GQ',
      'ER',
      'EE',
      'ET',
      'FK',
      'FO',
      'FJ',
      'FI',
      'FR',
      'GF',
      'PF',
      'TF',
      'GA',
      'GM',
      'GE',
      'DE',
      'GH',
      'GI',
      'GR',
      'GL',
      'GD',
      'GP',
      'GU',
      'GT',
      'GG',
      'GN',
      'GW',
      'GY',
      'HT',
      'HM',
      'VA',
      'HN',
      'HK',
      'HU',
      'IS',
      'IN',
      'ID',
      'IR',
      'IQ',
      'IE',
      'IM',
      'IL',
      'IT',
      'JM',
      'JP',
      'JE',
      'JO',
      'KZ',
      'KE',
      'KI',
      'KP',
      'KR',
      'KW',
      'KG',
      'LA',
      'LV',
      'LB',
      'LS',
      'LR',
      'LY',
      'LI',
      'LT',
      'LU',
      'MO',
      'MK',
      'MG',
      'MW',
      'MY',
      'MV',
      'ML',
      'MT',
      'MH',
      'MQ',
      'MR',
      'MU',
      'YT',
      'MX',
      'FM',
      'MD',
      'MC',
      'MN',
      'ME',
      'MS',
      'MA',
      'MZ',
      'MM',
      'NA',
      'NR',
      'NP',
      'NL',
      'NC',
      'NZ',
      'NI',
      'NE',
      'NG',
      'NU',
      'NF',
      'MP',
      'NO',
      'OM',
      'PK',
      'PW',
      'PS',
      'PA',
      'PG',
      'PY',
      'PE',
      'PH',
      'PN',
      'PL',
      'PT',
      'PR',
      'QA',
      'RE',
      'RO',
      'RU',
      'RW',
      'BL',
      'SH',
      'KN',
      'LC',
      'MF',
      'PM',
      'VC',
      'WS',
      'SM',
      'ST',
      'SA',
      'SN',
      'RS',
      'SC',
      'SL',
      'SG',
      'SX',
      'SK',
      'SI',
      'SB',
      'SO',
      'ZA',
      'GS',
      'SS',
      'ES',
      'LK',
      'SD',
      'SR',
      'SJ',
      'SZ',
      'SE',
      'CH',
      'SY',
      'TW',
      'TJ',
      'TZ',
      'TH',
      'TL',
      'TG',
      'TK',
      'TO',
      'TT',
      'TN',
      'TR',
      'TM',
      'TC',
      'TV',
      'UG',
      'UA',
      'AE',
      'GB',
      'US',
      'UM',
      'UY',
      'UZ',
      'VU',
      'VE',
      'VN',
      'VG',
      'VI',
      'WF',
      'EH',
      'YE',
      'ZM',
      'ZW',
    ],
  },
  appearance: {
    shirtsize: ['', 'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
    pantsize: ['', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    shoesize: ['', 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
  },
  work_conditions: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
  tax_card: {
    health_insurance_types: ['', 'private', 'statutory'],
    tax_classes: [1, 2, 3, 4, 5, 6],
    child_tax_allowances: [
      '',
      '0.0',
      '0.5',
      '1.0',
      '1.5',
      '2.0',
      '2.5',
      '3.0',
      '3.5',
      '4.0',
      '4.5',
      '5.0',
      '5.5',
      '6.0',
      '6.5',
      '7.0',
      '7.5',
      '8.0',
      '8.5',
      '9.0',
      '9.5',
      '10.0',
      '10.5',
      '11.0',
      '11.5',
      '12.0',
      '12.5',
      '13.0',
      '13.5',
      '14.0',
      '14.5',
      '15.0',
      '15.5',
      '16.0',
    ],
  },
  users: {
    role: ['', 'freelancer', 'field', 'client', 'admin', 'agent'],
    salutation: ['', 'F', 'M'],
  },
  contact: {
    salutation: ['', 'F', 'M'],
  },
  contacts: {
    categories: ['clients', 'site'],
  },
  orders: {
    state: ['', 'draft', 'active', 'closed'],
    initial: 'active',
  },
  projects: {
    state: ['draft', 'active', 'closed'],
    initial: 'active',
    category: [
      'none',
      'fragrance',
      'care',
      'visa',
      'cabin',
      'spray',
      'flyer',
      'wrap',
      'teasing',
    ],
    feedback: ['boolean', 'string'],
    brands: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18"
    ]
  },
  inherited: {
    state: ['draft', 'active'],
    initial: 'active',
    category: [
      'none',
      'fragrance',
      'care',
      'visa',
      'cabin',
      'spray',
      'flyer',
      'wrap',
      'teasing',
    ],
  },
  sites: {
    category: ['none', 'head-quarter', 'office'],
  },
  relationship: [
    'The person managed you directly',
    'The person reported you directly',
    "The person was senior to you but didn't manage directly",
    "You were senior to the person but didn't manage directly",
    'You worked with the person in same group',
    'The person worked with you but in different group',
    'you were a client to the person',
    'The person was your client',
    'The person mentored you',
    'You mentored the person',
  ],
  tenders: {
    federalStates: [
      '',
      'Baden-Württemberg',
      'Bayern',
      'Berlin',
      'Brandenburg',
      'Bremen',
      'Hamburg',
      'Hessen',
      'Mecklenburg-Vorpommern',
      'Niedersachsen',
      'Nordrhein-Westfalen',
      'Rheinland-Pfalz',
      'Saarland',
      'Sachsen',
      'Sachsen-Anhalt',
      'Schleswig-Holstein',
      'Thüringen',
    ],
    matching: ['matched', 'mismatched'],
    state: ['active', 'expired', 'scheduled'],
    initial: 'active',
    invalidationTime: '23:59:59',
    incentiveTypes: ['checkin', 'sales_report', 'picture_documentation'],
  },
  offers: {
    state: ['submitted', 'shortlisted', 'rejected'],
  },
  preferences: {
    languages: ['DE'],
    timezones: TimeZoneList,
  },
  freelancers: {
    statuses: ['active', 'unconfirmed', 'pending', 'not_registered', 'inactive',  'locked'],
  },
  legal: {
    documents: ['licence', 'permit', 'evidence'],
    tracked: [], // used for skipping creation of freelancer document (created after approval only)
    type_action_mapping: {
      // 'replace-freelancer-tradelicence': 'trade-licence',
      'replace-freelancer-workpermit': 'work-permit',
      // 'replace-freelancer-evidence': 'evidence'
    },
  },
  qualifications: {
    reference: {
      dates: false,
    },
  },
  assignments: {
    client: {
      states: ['open', 'tendered', 'booked', 'preparation,invoiced'],
    },
    others: {
      states: ['open', 'tendered', 'booked', 'preparation', 'invoiced'],
      client_invoice: ['not_invoiced', 'invoiced'],
      missing_docs: ['only_missing_docs'],
    },
    freelancer: {
      attributes: ['only_upcoming'],
      states: ['booked', 'preparation', 'invoiced'],
    },
  },
  budgets: {
    warningThreshold: 1000,
    errorThreshold: 0,
  },
  freelancer: {
    options: ['height', 'shirtsize', 'haircolor', 'pants', 'shoesize', 'hasDriversLicense'],
  },
  gtcs: {
    docTypes: ['terms-and-conditions', 'attachment'],
    confirmationTypes: ['none', 'upload-signed', 'checked'],
    reconfirmationIndexes: ['periodically', 'checkins-count'],
  },
  job: {
    offers: {
      limit: 100, // show first 100 entries
    },
  },
  certificates: {
    categories: ['brand', 'promotion', 'product'],
    recommendation: ['only_recommended', 'with_jobs'],
    attributes: ['only_recommended', 'only_enabled', 'only_exclusive'],
    legal: ['with_legal'],
  },
  skill_list: [],
  reports: {
    statuses: ['pending', 'accepted', 'rejected'],
  },
  invoices: {
    states: [
      'issued',
      'approved',
      'payment-authorized',
      'money-transfered',
      'rejected',
    ],
    preparation: {
      requiredDocumentTypes: {
        freelancer: ['report', 'picture-documentation'],
        other: ['questionnaire', 'report', 'picture-documentation'],
      },
      // allow multiple assignments per document
      allowMultiple: false,
    },
    attributes: ['only_with_sconto'],
  },
  postprocessing: {
    requiredDocumentTypes: {
      freelancer: ['report', 'picture-documentation'],
      other: ['questionnaire', 'report', 'picture-documentation'],
    },
    // allow multiple assignments per document
    allowMultiple: false,
  },
  accounting: {
    export: {
      types: ['sepa', 'accounting'],
      paymentTargetToShiftInDays: 7,
    },
    files: {
      types: ['sepa', 'accounting'],
    },
  },
  todos: {
    state: ['open', 'done'],
  },
  report: {
    state: ['active', 'onboarding', 'inactive', 'lock', 'pending'],
    ageGroup: ['18-25', '26-30', '31-35', '36-40', '41-45', '46-50', '51-55', '56-60', '61+'],
    gender: ['F', 'M', 'D'],
    pageSize: ['10', '25', '50', '100'],
    hasDriversLicense: [1, 0],
    hasOwnCar: [1, 0],
    languages: [
      'german',
      'english',
      'french',
      'turkish',
      'arabic',
      'italian',
      'spanish',
      'dutch',
      'polish',
      'czech',
      'other',
    ]
  },
  logs: {
    type: [
      'BudgetCreatedEvent',
      'OfferPlacedEvent',
      'OfferDeclinedEvent',
      'TenderDeclinedEvent',
      'FreelancerBookedEvent',
      'FreelancerUnbookedEvent',
      'DataChangedEvent',
      'TenderCreatedEvent',
      'TenderClosedEvent',
      'UserRequestProcessedEvent',
      'UserRequestDeclinedEvent',
      'CheckinUpdatedEvent',
      'CheckinCreatedEvent',
      'InvoiceAcceptedEvent',
      'InvoiceRejectedEvent',
      'JobMessageCreatedEvent',
      'TenderExpiredEvent',
      'UserDeletedEvent',
      'FreelancerDeletedEvent',
    ],
  },
  mails: {
    statuses: ['active', 'pending'],
    assignmentStates: ['only_upcoming'],
  },
  jobs: {
    attributes: ['with_offer'],
  },
  health_insurances: {
    types: ['', 'private', 'statutory'],
  },
  currency: [
    "USD",
    "EUR",
    "GBP"
  ],
  radius: [
    '10',
    '25',
    '50',
    '100',
    '150',
    '200'
  ],
  rate_types: ['per_hour', 'per_shift']
};
